version: 2.1
executors:
  docker-vars:
    environment:
      IMAGE_NAME: amramadan/hello1-circleci
    docker:
      - image: circleci/python:3.6.4
jobs:
  test:
    executor: docker-vars
    steps:
      - checkout
      - run:
          name: Running django tests
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run python manage.py test
  build:
    executor: docker-vars
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archiving Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: docker-vars
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Loading archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publishing to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
